baseURL = "https://research.dwanat.eu"
languageCode = 'en-us'
title = 'Dominika Wanat'
theme = 'lynx'
enableEmoji = true
disableKinds = ["taxonomy","term"]
timeZone = "Europe/Warsaw"
relativeURLs = false
enableGitInfo = true
staticDir2 = "static"


[params.author]
    name = "Dominika Wanat"
    headline = "PhD student | Psychometrics | QoE | AGH University"
    image = "avatar.png"
    links = [
        # {link={href="",text="Full paper",icon="file-solid"}},
        # {link={href="",text="Dataset",icon="database-solid"}},
        #{handshake={text="ACMMM '25",href="https://acmmm2025.org"}},
        { email = "mailto:wanat@agh.edu.pl" },
        { orcid = "https://orcid.org/0000-0002-8790-5114"},
        { linkedin = "https://linkedin.com/in/dwanat"},
        { github="https://github.com/doma2203"}
    ]