baseURL = "https://research.dwanat.eu"
languageCode = 'en-us'
title = 'Dominika Wanat'
theme = 'lynx'
enableEmoji = true
disableKinds = ["taxonomy","term"]
timeZone = "Europe/Warsaw"
relativeURLs = false
enableGitInfo = true
staticDir2 = "static"


[params.author]
    name = "Dominika Wanat"
    headline = "PhD student | Psychometrics | QoE | AGH University"
    image = "avatar.png"
    links = [
        # {link={href="",text="Full paper",icon="file-solid"}},
        # {link={href="",text="Dataset",icon="database-solid"}},
         { handshake={text="Let's meet at the ACMMM'25!",href="https://whova.com/embedded/session/sa54pNCpHUFy1OTIEiEzceQu5kPuSm3dYlEnqAJdV4o%3D/4938778/?widget=primary"}},
         {file= {href="https://dl.acm.org/doi/10.1145/3746027.3755852",text="ACMMM'25 paper"}},
        { file = {href="https://doi.org/10.15199/59.2025.4.113",text=":poland: KRiT 2025"}},
        # { presentation = {href="https://doi.org/10.15199/59.2025.4.113",text=":poland: KRiT 2025"}},
        { email = "mailto:wanat@agh.edu.pl" },
        { orcid = "https://orcid.org/0000-0002-8790-5114"},
        { linkedin = "https://linkedin.com/in/dwanat"},
        { github="https://github.com/doma2203"}
    ]